version: 2

updates:
  - package-ecosystem: github-actions
    directories:
      - /
      - /.github/actions/prepare
      - /.github/actions/sidecar
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore"
    groups:
      actions:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      actions-majors:
        patterns:
          - "*"
        update-types:
          - major

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore"
    ignore:
      - dependency-name: muda
      - dependency-name: tray-icon
      - dependency-name: windows-future
        update-types:
          - version-update:semver-major
      - dependency-name: "tauri*"
        update-types:
          - version-update:semver-minor
          - version-update:semver-major
    groups:
      rust:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      rust-majors:
        patterns:
          - "*"
        update-types:
          - major

  - package-ecosystem: npm
    directory: /app
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore"
    ignore:
      - dependency-name: "@tauri-apps/*"
        update-types:
          - version-update:semver-minor
          - version-update:semver-major
    groups:
      picker:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      picker-majors:
        patterns:
          - "*"
        update-types:
          - major

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 1
    commit-message:
      prefix: "chore"
