[package]

name = "linkunbound-settings"

version.workspace = true

edition.workspace = true

rust-version.workspace = true

license.workspace = true

publish.workspace = true



[lints]

workspace = true



[lib]

name = "linkunbound_lib"

crate-type = ["staticlib", "cdylib", "rlib"]



[build-dependencies]

tauri-build = { workspace = true }



[dependencies]

base64.workspace = true

linkunbound-core.workspace = true
linkunbound-shell.workspace = true

tauri.workspace = true

tauri-plugin-single-instance.workspace = true

tauri-plugin-global-shortcut.workspace = true

serde.workspace = true

thiserror.workspace = true



[target."cfg(windows)".dependencies]

linkunbound-win.workspace = true
