[package]
name = "linkunbound-mac"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
linkunbound-core.workspace = true
thiserror.workspace = true

[lib]
name = "linkunbound_mac"

[target."cfg(target_os = \"macos\")".dependencies]
objc2 = "0.6"
block2 = "0.6"
objc2-foundation = { version = "0.3", default-features = false, features = [
  "std",
  "NSArray",
  "NSBundle",
  "NSDictionary",
  "NSError",
  "NSEnumerator",
  "NSGeometry",
  "NSObject",
  "NSString",
  "NSURL",
  "NSUserDefaults",
] }
objc2-service-management = { version = "0.3", default-features = false, features = [
  "std",
  "objc2",
  "objc2-foundation",
  "SMAppService",
] }
objc2-app-kit = { version = "0.3", default-features = false, features = [
  "std",
  "objc2-core-foundation",
  "block2",
  "NSEvent",
  "NSPasteboard",
  "NSResponder",
  "NSRunningApplication",
  "NSScreen",
  "NSWorkspace",
] }
